### ISSUE TITLE
Feature request (nice-to-have): reintroduce subscan extrinsic links

### ISSUE THREAD

**Issue by lovelaced** [paritytech/polkadot-testnet-faucet#104]
This actually used to be the case in the codebase we inherited, but the subscan linking has been taken out. It would be nice to:

1) check to see if the chain is actually on subscan (they have an API),
2) set the extrinsic hash sent to the user as a clickable link which leads them directly to the extrinsic, for example:

Sent @erin:matrix.parity.io 1000 ROCs. Extrinsic hash: 0x8b2d46b53c5caa454f29d674a9cadbf14b5b0aa3d61395bc90c84e2d2f343249

links to -> https://rococo.subscan.io/extrinsic/0x8b2d46b53c5caa454f29d674a9cadbf14b5b0aa3d61395bc90c84e2d2f343249

**Comment by mutantcornholio** [comment]
Here we go

<img width="595" alt="Screen Shot 2023-06-21 at 12 27 12" src="https://github.com/paritytech/polkadot-testnet-faucet/assets/588262/740534eb-2094-4a63-a864-f3919c0cc028">

<img width="593" alt="Screen Shot 2023-06-21 at 12 26 57" src="https://github.com/paritytech/polkadot-testnet-faucet/assets/588262/2548528b-3486-40d0-9a2f-fdf942e58dd9">
