### ISSUE TITLE
Support for Westmint / NFT

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-testnet-faucet#152]
Similar to #151 and for the same reasons, it would be good to supported the minting and issusing of NFT via faucet drips. 

Some related context: 
- https://substrate.stackexchange.com/questions/8798/how-to-transfer-wnd-tokens-from-westend-going-to-westmint-to-mint-fungible-toke
- https://substrate.stackexchange.com/questions/8789/westend-westmint-difficulty-in-minting-a-fungible-asset-in-westmint/8793#8793

**Comment by mutantcornholio** [comment]
Just as we had a discussion about Assets in the neighbouring issue, could you provide some more context on how faucet should handle minting NFTs?

Both questions that you linked are about teleporting westies to Westmint, not about issuing NFTs directly from faucet

**Comment by chevdor** [comment]
I don't think we MUST issue from the faucet. Let's make it simple as you suggested:
The faucet can drip any of the tokens it has in stock. We may want to have a white list to prevent abuse though.
I would leave the minting aside for now and let humans deal with minting and sending tokens to the faucet.

**Comment by mutantcornholio** [comment]
> The faucet can drip any of the tokens it has in stock. We may want to have a white list to prevent abuse though.

Are we still talking about NFTs?

**Comment by chevdor** [comment]
NFTs... sorry, I was tuned on Assets... 
I think we have already a piece of software used to provide NFTs to attendees of conferences.
I don't know where this piece of code is but we could use a simplified version of it (ie the same without the need for a "code").

With NFT is that we should only allow `N` per account (with N=3 or such a low number). Inline with my previous answer, I would let a human issue some NFT and transfer them to the faucet for dripping.

@jsidorenko surely has cool ideas of what and how we could do.

**Comment by chevdor** [comment]
As a user, I want the faucet to send me a NFT.

**Comment by mutantcornholio** [comment]
To do what?

**Comment by jsidorenko** [comment]
> Any random NFT? Why is this valuable? Faucet now provides a way to get testing currency so developers would be able to test their apps. What kind of user problem are you trying to solve?

There are a lot of cases when for testing purposes you need to quickly mint some dummy NFT to validate the UI/Transfer flow/etc..

**Comment by jsidorenko** [comment]
we can create an open collection where anyone would be able to mint a dummy NFT, but that NFT won't have any metadata associated (no image), so I doubt it would be of any value for testing

**Comment by jsidorenko** [comment]
> I think we have already a piece of software used to provide NFTs to attendees of conferences.
I don't know where this piece of code is but we could use a simplified version of it (ie the same without the need for a "code").

that's here: https://github.com/paritytech/uniques-campaign-runner

**Comment by chevdor** [comment]
It could but you can make it simpler. Instead of the faucet minting on demand, a user (like you, I , Jegor, etc...) can premint and send all the NFTs to the faucet.

So when a user requests a NFT, there is nothing to mint, we already have some NFTs ready to be sent, just like WNDs.
As @jsidorenko mentioned, we don't really need any image.

> So, it would drip only NFTs of single faucet's collection.

That would work for me yes. Handling several collections means the user could chose... or the faucet could pick one random collection depending on what is in stock.

**Comment by mutantcornholio** [comment]
After another discussion, we've decided not to implement it.  

Original stackexchange questions were related to teleporting test tokens, in order to make NFTs, which is already done.  
And we also haven't received any more requests for creation of NFTs right inside of faucet.
