### ISSUE TITLE
Make sure the faucet continues to work when there is a runtime upgrade

### ISSUE THREAD

**Issue by rzadp** [paritytech/polkadot-testnet-faucet#223]
Right now, when there is a runtime upgrade, the faucet fails with `1010: Invalid Transaction: Transaction has a bad signature` until it is restarted.

Maybe we could include a runtime upgrade in the E2E test and check that it continues to work?

### Possible solutions

I don't know the exact cause of failure, so I don't know what the solutions might be.
But potentially:

- Change HTTP provider to WS provider
- See if we're using the HTTP provider somehow incorrectly?

**Comment by mutantcornholio** [comment]
Reopening the issue, as changing the provider didn't actually fix the problem

**Comment by mutantcornholio** [comment]
Moving to blocked until next occurrence

**Comment by mordamax** [comment]
afaik devops team has it in a list of todo - to restart faucets.. @PierreBesson @ArshamTeymouri correct?
