### ISSUE TITLE
Rename this repository to substrate-faucet

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot-testnet-faucet#237]
As this faucet now supports token drips from web request, we should rename it `substrate-matrix-faucet` -> `substrate-faucet`.

**Comment by Bullrich** [comment]
@mutantcornholio will [paritytech/gitspiegel](https://github.com/paritytech/gitspiegel) handle this change?

I believe that is our only blocker.

**Comment by mordamax** [comment]
@alvicsam ^^

**Comment by mutantcornholio** [comment]
> @mutantcornholio will [paritytech/gitspiegel](https://github.com/paritytech/gitspiegel) handle this change?
> 
> I believe that is our only blocker.

It should. gitspiegel is configured using node ids, which should not change with renaming.

**Comment by Bullrich** [comment]
@mutantcornholio @mordamax  paritytech/security#9 has been merged. Can we now rename the repo to `polkadot-testnet-faucet`?

**Comment by mordamax** [comment]
yep, perfect name imo

**Comment by Bullrich** [comment]
Project has been renamed.
