### ISSUE TITLE
Funds not showing up, but extrinsic is successful

### ISSUE THREAD

**Issue by DoubleOTheven** [paritytech/polkadot-testnet-faucet#286]
### Faucet Type

Web

### Problem

When I use [this faucet](use.ink/faucet) for Contracts on Rococo I get a [successful extrinsic](https://rococo.subscan.io/extrinsic/0xa8b79291cd62edd2c0885a396602a5933891d513c1747138e3bb82fe4310cad9) in Subscan, but funds do not show up in my wallet.

### Address

5HTUvv1iS2yAMsAVJhUc8TKy3XxV4A1e1bT8Sd1Y6NmCeWYj

### Network ID

1002

### Relevant log output

```Shell
https://rococo.subscan.io/extrinsic/0xa8b79291cd62edd2c0885a396602a5933891d513c1747138e3bb82fe4310cad9
```

**Comment by rzadp** [comment]
@KiChjang Hey, could you provide some assistance on this one?

This causes the testnet faucets to fail teleporting assets.

I have described some more details [here](https://github.com/paritytech/polkadot/pull/7098#issuecomment-1587478247).

**Comment by PierreBesson** [comment]
Personally, I'm able to do teleport transfer just fine using our [python code in the testnet-manager](https://github.com/paritytech/testnet-manager/blob/main/app/lib/balance_utils.py#L50).
Here is the extrinsic we submitted on Rococo: https://rococo.subscan.io/extrinsic/0xd84ddc6762d1d3222badeb6219297bf9c7d2987080f897610cfae212cf5c81e6

Note that if you manage to do it properly using polkadot.js, you should also contribute it to polkadot.js apps : https://github.com/polkadot-js/apps/issues/9127

**Comment by rzadp** [comment]
@DoubleOTheven You should be able to drip now, the issue has been resolved.

**Comment by rzadp** [comment]
> Note that if you manage to do it properly using polkadot.js, you should also contribute it to polkadot.js apps : [polkadot-js/apps#9127](https://github.com/polkadot-js/apps/issues/9127)

@PierreBesson It's been [done separately](https://github.com/polkadot-js/apps/pull/9529) and is now visible in the UI.

<img width="306" alt="Screenshot 2023-06-19 at 09 53 57" src="https://github.com/paritytech/polkadot-testnet-faucet/assets/12039224/0d85f411-5a01-4148-ba0d-121bf8bb7aad">

Although I'm still in the dark on why `limitedTeleportAssets` works while `teleportAssets` does not. 🤔
