### ISSUE TITLE
Move non-secret chain data away from env to local configs

### ISSUE THREAD

**Issue by mutantcornholio** [paritytech/polkadot-testnet-faucet#298]
Currently, [our config](https://github.com/paritytech/polkadot-testnet-faucet/blob/main/env.faucet.config.json#L10-L54) holds data like `FAUCET_BALANCE_CAP`, `INJECTED_TYPES`, `NETWORK_DECIMALS`, `RPC_ENDPOINT`, `DRIP_AMOUNT`.  
Updating such network-specific data is tedious and in many cases requires changing both code and deployment configuration.  

As all this data isn't secret and basically provides configuration for specific network for the faucet, I suggest we do something like [networkData.ts](https://github.com/paritytech/polkadot-testnet-faucet/blob/main/client/src/lib/utils/networkData.ts) (or even reuse that one), so the deployment configuration would only have network name, and everything else would be picked from code.  

Also, `SMF_BOT` and `SMF_BACKEND` prefixes are kinda outdated as they are integrated now. Would be great to discontinue them at some point.

**Comment by rzadp** [comment]
I like this idea. 👍

**Comment by PierreBesson** [comment]
I think we should keep a way to configure those values by env vars because as far as I can see it has the side effect of making those not configurable externally when deploying the faucet to other networks (eg. parachains).

**Comment by mutantcornholio** [comment]
> I think we should keep a way to configure those values by env vars because as far as I can see it has the side effect of making those not configurable externally when deploying the faucet to other networks (eg. parachains).

That's a trade-off that we conciously went for. The upside for us is that configuration updates won't require updating several repositories and waiting for approvals outside of our team.  

Uncontrollable growth of amount of configuration variables is another problem that's addressed by having the configuration together with code.
