### ISSUE TITLE
📡 Problem with the Faucet

### ISSUE THREAD

**Issue by mordamax** [paritytech/polkadot-testnet-faucet#301]
### Faucet Type

Matrix

### Problem

Sometimes transaction failed with message "Priority is too low"

Related: https://stackoverflow.com/questions/63475813/transaction-failed-error-1014-priority-is-too-low-515000139-vs-515000139

![image](https://github.com/paritytech/polkadot-testnet-faucet/assets/1177472/f384266c-32f0-4d75-b92f-df05708562a1)

```
Norbert
!drip 5CtnTz6MA7S6EvNmjgpsGbZDmLd796er716WvXJPG6hVSsh7 200

Rococo Faucet Bot
Sent [@norbert:parity.io](https://matrix.to/#/@norbert:parity.io) 200 ROCs. Extrinsic hash: 0xed8c44a283f2d761f0a4f78c2fcb2bec1a5dd4b75b27a55c09d789567cffa1f0
1014: Priority is too low: (12066 vs 12066): The transaction has too low priority to replace another transaction already in the pool.
```

### Network ID

Rococo | Westend

**Comment by mutantcornholio** [comment]
so, everything I could find about the error suggests that we use `{ nonce: -1 }` for the `signAndSend` calls (which we already do).  
Also, the cases don't look like we're spamming transactions.  
It happens from time to time, but it's not something that we can reproduce.  
All the related issues in polkadot-js/api are [closed as stale](https://github.com/polkadot-js/api/issues?q=is%3Aissue+too+low).  

I suggest to close this one as well.
