### ISSUE TITLE
Increase amount of tokens 🪙 given by Westend Faucet

### ISSUE THREAD

**Issue by Bullrich** [paritytech/polkadot-testnet-faucet#302]
Currently westend faucet only provides 1 token. 

I had received a request by someone in the company to increase this amount.

We should increase this to 10 and update the FAQ so it has this information

Blocked by: https://forum.parity.io/t/incrementing-the-westend-faucet-drip/1916

**Comment by mutantcornholio** [comment]
done: https://github.com/paritytech/polkadot-testnet-faucet/pull/316
