### ISSUE TITLE
Add subdomain for easy access

### ISSUE THREAD

**Issue by itsbirdo** [paritytech/polkadot-testnet-faucet#348]
### Faucet Type

Web

### Problem

It would be great if we can add a subdomain to the faucet for easy access - this will improve the ability for developers to be able to remember the faucet address.

Suggestion:
faucet.polkadot.network

cc: @Bullrich 

### Network ID

Relay Chain

**Comment by lovelaced** [comment]
it is pretty awesome it already shows up at the first result on google when searching "polkadot faucet" though :D

**Comment by mordamax** [comment]
@lovelaced @itsbirdo may be instead of polkadot.network we could have it like faucets.parity.io?
since the testnets (rococo and westend) are effectively managed by parity, not by w3f

that would be fair and yet easier

From the SEO perspective faucet could be adjusted to respond on "polkadot faucet" requests in google, so should be fine IMO

**Comment by mordamax** [comment]
@lovelaced @itsbirdo i guess if no one against it so far, so I will prepare PR to deploy this to faucets.parity.io until we have more clarity about *.polkadot.network. If we have more info there - then there will be no problem to 301 redirect to a better domain

**Comment by PierreBesson** [comment]
@mordamax, I can suggest to use `faucets.polkadot.io`. @lovelaced @itsbirdo would that be okay for you ?

**Comment by lovelaced** [comment]
Works for me!

**Comment by Bullrich** [comment]
I'm looking forward to it 🤩 

I don't know who manages the webadmin for polkadot.io, but setting it up would be as simple as setting the custom domain in the [pages configuration](https://github.com/paritytech/polkadot-testnet-faucet/settings/pages) and then configuring the DNS.

**Comment by Bullrich** [comment]
New webiste has been configured by @mordamax!

## Find the faucet in [faucet.polkadot.io](https://faucet.polkadot.io/)

**Comment by KarimJedda** [comment]
Birdo's announcement here: https://twitter.com/itsbirdo_/status/1770422620095193370

Excellent job team!! :rocket:
