### ISSUE TITLE
Element faucet does not work with parachains

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-testnet-faucet#361]
### Faucet Type

Matrix

### Problem

When I drip account directly on relay chain, it works:
```
!drip 5Grz3bj38VJ1P73TsKk7ZX5gQa4qUZWjrHgGV3p6cvYTwAqA 100

Sent [@branislav_kontur:parity.io](https://matrix.to/#/@branislav_kontur:parity.io) 100 ROCs.
Extrinsic hash: [0x845f07c589fc115e174546b19fbc0f2e8223b51ebb5292d23a3ae85d1b9a5e18](https://rococo.subscan.io/extrinsic/0x845f07c589fc115e174546b19fbc0f2e8223b51ebb5292d23a3ae85d1b9a5e18)
```

But when I want to drip some account on Rococo's parachain here: https://matrix.to/#/#rococo-faucet:matrix.org :
```
!drip 5Grz3bj38VJ1P73TsKk7ZX5gQa4qUZWjrHgGV3p6cvYTwAqA:1002 100
```
it fails with error:
```
createType(StagingXcmV3Junction):: DoNotConstruct: Cannot construct unknown type StagingXcmV3Junction
```

![image](https://github.com/paritytech/polkadot-testnet-faucet/assets/8159517/a1b21acd-0634-471f-95a2-baa908732cf6)

### Network ID

Rococo

**Comment by bkontur** [comment]
could be related to the https://github.com/paritytech/polkadot-sdk/pull/1948

**Comment by mutantcornholio** [comment]
hmm, [the fix](https://github.com/paritytech/polkadot-testnet-faucet/pull/355) to this was merged, yet wasn't released...
Deploying it now: https://gitlab.parity.io/parity/opstooling/substrate-matrix-faucet/-/pipelines/413889

**Comment by mutantcornholio** [comment]
Fixed
<img width="635" alt="Screen Shot 2023-11-15 at 12 06 24" src="https://github.com/paritytech/polkadot-testnet-faucet/assets/588262/1b132e5c-0e69-4bd1-a10f-cbb578f57a05">
