### ISSUE TITLE
Understandability/layout

### ISSUE THREAD

**Issue by lovelaced** [paritytech/polkadot-testnet-faucet#365]
Hey there,

This is more just general feedback, but it seems to me that "Network" and "Chain" are kind of confusing terms. Instead of mixing relay and parachains I think it would make more sense for the selectors to look like this:

Network     |    Chain
------------------------
Rococo      |    Relay (default), Contracts, Asset Hub, Trappist, etc
Westend    |     Relay (default), Asset Hub, etc
Paseo         |    Relay (default), Asset Hub, Contracts, etc
// etc

Right now it seems a bit confusing and backwards from what I'd expect. 

In addition, the colors seem a bit difficult to see (using Chrome on MacOS) and the mouseover effect is barely discernable.

<img width="288" alt="Screenshot 2023-12-11 at 16 22 23" src="https://github.com/paritytech/polkadot-testnet-faucet/assets/8581604/7eda2ad7-74f9-4618-bf8a-415a8c2cb718">

Looking great though! I imagine once Paseo launches this will get a lot of new visitors :)

**Comment by helloitsbirdo** [comment]
+1 on the colour highlight issues
