### ISSUE TITLE
[EngAut] Faucets Q1 iteration

### ISSUE THREAD

**Issue by mordamax** [paritytech/polkadot-testnet-faucet#369]
```[tasklist]
### Tasks
- [ ] #348
- [ ] #277
- [ ] #365
- [ ] https://github.com/paritytech/polkadot-testnet-faucet/issues/370
```

**Comment by mordamax** [comment]
Weekly update:
- Fixed some UX/UI issues https://github.com/paritytech/polkadot-testnet-faucet/issues/365
- https://github.com/paritytech/polkadot-testnet-faucet/issues/370
  - Added Paseo to Web faucet
  - Modified default Paseo drip amount to 100 and daily cap to 500
  - Replaced the default *.parity.io and W3F whitelist with list of specific people for Paseo

**Comment by mordamax** [comment]
No updates on this from last week

**Comment by Bullrich** [comment]
PR for #277 has been created:
- https://github.com/paritytech/polkadot-testnet-faucet/pull/383
