### ISSUE TITLE
📡 Problem with the Faucet

### ISSUE THREAD

**Issue by daniel521854** [paritytech/polkadot-testnet-faucet#389]
### Faucet Type

Web

### Problem

not getting faucet kindly send it on 5Gsw6WA8QaoM4SoALp78XTmTG1bzJNqhPKH6JHFMYifLxRkS 
and kindly also fix it on website

### Network ID

Relay Chain

**Comment by mordamax** [comment]
https://github.com/availproject/polkadot-testnet-faucet
