### ISSUE TITLE
📡 Problem with the Faucet

### ISSUE THREAD

**Issue by betaocryptorj** [paritytech/polkadot-testnet-faucet#390]
### Faucet Type

Web

### Problem

The AVL coins do not reach my wallet  5CSohpNpwb3Ye9ZbxXQUMtfkXfJMabvQKSBS8gCCy4DpvPFt 
I tried twice already (today and yesterday) and nothing so far. I need that as soon as possible to mint NFT from  Light node Challenger.

### Network ID

Relay Chain

**Comment by mordamax** [comment]
Wrong repo: https://github.com/availproject/polkadot-testnet-faucet
