### ISSUE TITLE
📡 Problem with the Faucet

### ISSUE THREAD

**Issue by WarathatPan** [paritytech/polkadot-testnet-faucet#391]
### Faucet Type

Web

### Problem

Avail Faucet didn't working. Successfully sent AVLs to your address but not have transaction and AVLs token to my address
<img width="617" alt="image" src="https://github.com/paritytech/polkadot-testnet-faucet/assets/26578782/7b82e3e4-5784-4eab-8c4d-50eed8f3b277">

### Network ID

Avail Chain

**Comment by mordamax** [comment]
https://github.com/availproject/polkadot-testnet-faucet
