### ISSUE TITLE
📡 Problem with the Faucet

### ISSUE THREAD

**Issue by raviriley** [paritytech/polkadot-testnet-faucet#415]
### Faucet Type

Web

### Problem

Error: Unsupported signed-extension: CheckMetadataHash

### Address

5CyYePoS6W2ynh16fqw2RZbHCEcYDyAbpYAnt3z8TdR3QKT5

### Network ID

Relay Chain

### Relevant log output

```Shell
Error: Unsupported signed-extension: CheckMetadataHash
```

**Comment by mutantcornholio** [comment]
Seems that this PR https://github.com/paritytech/polkadot-sdk/pull/4274 broke rococo for all the clients, and requires clients to change their code.
