### ISSUE TITLE
single use per day restriction is too much

### ISSUE THREAD

**Issue by PieWol** [paritytech/polkadot-testnet-faucet#427]
### Faucet Type

Web

### Problem

What is the reason to restrict the faucet so heavily? 1 request per day per network + it's parachains? Why would you ever do this. This is the most anti dev thing I can imagine.

I can see that there needs to be a cap to make it annoying to stress the faucet, but why not raise it to something like 20 usages per day? So that you could actually get something done if you need to? I mean imagine having to wait 24 hours just because you accidentally selected the wrong chain / wrong account. 

### Network ID

Relay Chain

**Comment by itsbirdo** [comment]
Hi @PieWol thanks for the feedback. We've discussed it internally and we'll increase the faucet limit per drip. 
As an FYI rococo is being deprecated for Paseo (https://github.com/paseo-network/.github).

**Comment by PieWol** [comment]
Hello @itsbirdo birdman!
That sounds great 👍
When will this change?

**Comment by mordamax** [comment]
Since rococo is already deprecated i will close this issue. The paseo already has a larger default amount
