### ISSUE TITLE
Address issues raised by Andrei

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-testnet-faucet#85]
see comments in #83 

- [x] ✂️ — about a empty @returns,
- [ ] #faucetBalance — i know what it, I asked why we use js private here, why not ts private?
- [ ] "Better move it to constant out of scope", Not critical, but we initialize constant value on every call
- [ ] [].join('') — So we write code for humans, not for machines :-)
- [ ] "But here we create and apply actions" - It's a name of a function. createAndAplyActions
- [ ] "Maybe we can define it in another module?" - ...

**Comment by mordamax** [comment]
The code was refactored a lot after this followup, so closing
