### ISSUE TITLE
Add new Prometheus metric to help estimate the time until next refill

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-testnet-faucet#90]
Since #83 we have a balance metric. That helps answering the question "is it time to refill" but tells us nothing what timing. For instance, we dispense 1 WND on Westend but 100x more on Rococo.

I suggest we introduce an additionnal new metrics called along the lines of `remaining_tip_count` which is the free balance of the faucet dvided by the size of the drip. That will help guestimate how long the faucet can run at current pace until a new refill is required.

**Comment by mordamax** [comment]
@chevdor what is the threshold for westend and rococo which tells you that's a time to refill? like < 1,000 WND ? or 10,000 ROC...

**Comment by chevdor** [comment]
Currently, there is no alert and we use a single threshold for both.
It does not make much sense to have one single threshold as it is currently done in the dashboard since the tokens have different "value" and the number of user requests also varies per network.,

In the dashboard currently we have the following and it has been working ok:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/738724/165726756-3538e703-e883-4e5d-a75b-e3ca5485786d.png">

The goal with alerts is to spot the need to refill early enough so devops have time to reload "at their convenience" without always ending up in an emergency when the faucet is already dry.

I don't think a hard threshold is ideal as the faucet balance may remain stable for a while then plunge due to many more requests for some reasons (event, tweet, etc...).

Since the networks we target have no value, we cannot use that.

The amount of drips is counted by the faucet internally so we should be able to estimate an ETA and report that in the prometheus metrics. It can be a number of hours until estimated depletion.

It is clear that such an ETA could be in 2w, then comes a huge drip from Parity or Web3 and the ETA falls to 2d. At least having this ETA metric, devops can set alerts based on the value itself or the decreasing rate or even both.

When the faucet starts, unless we implement some persistence, we will have very little data and not enough to produce good a good **value over time**. We should take it into account and not report anything until we conside the value usable. I would start with waiting 1 hour. We don't really need persistence we Grafana and the Alert Manager could keep using the last seen value until we provide something better.

Grafana/ Prom miss a value to do this esttimation: we do provide the requests rate but those services don't know the value of the drip so they cannot estimate if a balance of 1000 will last 1 hour or a 1month. The faucet has this information.

**Comment by mordamax** [comment]
Done
